export const PROCESS_EXIT_CODE = 1;

const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

export const API_RESPONSE_CODE = {
	BAD_REQUEST,
	UNAUTHORIZED,
    NOT_FOUND,
    INTERNAL_SERVER_ERROR
};
